---
- hosts: splunk-enterprise
  tasks: 
  - name: Download Splunk software package
    get_url:
      url: https://download.splunk.com/products/splunk/releases/9.1.3/linux/splunk-9.1.3-d95b3299fa65.x86_64.rpm
      dest: /opt
      mode: '0644'

  - name: Install Splunk Enterprise Software Package
    yum:
      name: /opt/splunk-9.1.3-d95b3299fa65.x86_64.rpm
      state: present

  - name: Accept Splunk License
    command: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd password

  - name: Start Splunk Service
    command: /opt/splunk/bin/splunk start

  - name: Change splunk folder ownership
    command: chown -R splunk:splunk /opt/splunk

  - name: Stop Splunk Service
    command: /opt/splunk/bin/splunk stop

  - name: Enable splunk service at boot time
    command: /opt/splunk/bin/splunk enable boot-start

  - name: Change Splunk
  
